name:                http2warp
version:             0.1.0.0
github:              "kirisaki/http2warp"
license:             BSD3
author:              "Akihito KIRISAKI"
maintainer:          "kirisaki@klaraworks.net"
copyright:           "Copyright: (c) 2018 Akihito KIRISAKI"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kirisaki/http2warp#readme>

dependencies:
- base >= 4.7 && < 5
- http-types
- case-insensitive
- text
- wai
- warp
- warp-tls

library:
  source-dirs: src

executables:
  http2warp:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - http2warp

tests:
  http2warp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - http2warp
